apiVersion: v1
kind: Service
metadata:
  name: nodejs-gitops-service
  namespace: default
spec:
  selector:
    app: nodejs-gitops-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
